# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{active_mongo}
  s.version = "0.3.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Mantas Masalskis"]
  s.date = %q{2010-02-06}
  s.description = %q{Schemaless Mongo ORM for Rails 3.0}
  s.email = %q{mantas@idev.lt}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.textile"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.textile",
     "Rakefile",
     "VERSION",
     "active_mongo.gemspec",
     "lib/active_mongo.rb",
     "lib/active_mongo_attr_accessible.rb",
     "lib/active_mongo_collection.rb",
     "lib/active_mongo_has_many.rb",
     "lib/active_mongo_indexes.rb",
     "lib/active_mongo_instance.rb",
     "lib/active_mongo_named_scopes.rb",
     "lib/active_mongo_scope.rb",
     "lib/active_mongo_start.rb",
     "lib/active_mongo_uniquenesss.rb",
     "test/helper.rb",
     "test/test_active_mongo.rb"
  ]
  s.homepage = %q{http://github.com/mantas/ActiveMongo}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Schemaless Mongo ORM for Rails 3.0}
  s.test_files = [
    "test/helper.rb",
     "test/test_active_mongo.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

